### ISSUE TITLE
"node is not defined" when referencing node data in x-node

### ISSUE THREAD

**Issue by wrabit** [copyfactory/AlpineFlow#1]
https://codepen.io/willabbott/pen/KKOVBjO
(click console)

The output correctly shows the data from `x-text="node.id"` but there is an error in console. Just wondering what the correct approach is here?

**Comment by copyfactory** [comment]
Hi @wrabit yes this is normal as the node reference doesn't exist yet. I should update the examples to always include 'x-ignore'.

Best practice is to add an x-ignore directive to the first child so that Alpine doesn't crawl it. All x-ignore directives are removed when rendering a new node instance.
```
<div
    x-data="{isOpen: false, props: {}}"
    x-cloak
    x-node="{type: 'myNode', deletable: true, allowBranching: false, allowChildren: true}"
>
    <!--  Prevent crawling of the node  -->
    <div x-ignore>
        <div x-init="console.log(node.id)"></div>
    </div>
</div>

```
